# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Johan\Documents\Bella\game_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Johan\Documents\Bella\game_2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Johan\Documents\Bella\game_2\CMakeFiles C:\Users\Johan\Documents\Bella\game_2\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Johan\Documents\Bella\game_2\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GAYME

# Build rule for target.
GAYME: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 GAYME
.PHONY : GAYME

# fast build rule for target.
GAYME/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/build
.PHONY : GAYME/fast

gamestate.obj: gamestate.cc.obj
.PHONY : gamestate.obj

# target to build an object file
gamestate.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/gamestate.cc.obj
.PHONY : gamestate.cc.obj

gamestate.i: gamestate.cc.i
.PHONY : gamestate.i

# target to preprocess a source file
gamestate.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/gamestate.cc.i
.PHONY : gamestate.cc.i

gamestate.s: gamestate.cc.s
.PHONY : gamestate.s

# target to generate assembly for a file
gamestate.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/gamestate.cc.s
.PHONY : gamestate.cc.s

main.obj: main.cc.obj
.PHONY : main.obj

# target to build an object file
main.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/main.cc.obj
.PHONY : main.cc.obj

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/main.cc.s
.PHONY : main.cc.s

motion.obj: motion.cc.obj
.PHONY : motion.obj

# target to build an object file
motion.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/motion.cc.obj
.PHONY : motion.cc.obj

motion.i: motion.cc.i
.PHONY : motion.i

# target to preprocess a source file
motion.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/motion.cc.i
.PHONY : motion.cc.i

motion.s: motion.cc.s
.PHONY : motion.s

# target to generate assembly for a file
motion.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/motion.cc.s
.PHONY : motion.cc.s

object.obj: object.cc.obj
.PHONY : object.obj

# target to build an object file
object.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/object.cc.obj
.PHONY : object.cc.obj

object.i: object.cc.i
.PHONY : object.i

# target to preprocess a source file
object.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/object.cc.i
.PHONY : object.cc.i

object.s: object.cc.s
.PHONY : object.s

# target to generate assembly for a file
object.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/object.cc.s
.PHONY : object.cc.s

player.obj: player.cc.obj
.PHONY : player.obj

# target to build an object file
player.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/player.cc.obj
.PHONY : player.cc.obj

player.i: player.cc.i
.PHONY : player.i

# target to preprocess a source file
player.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/player.cc.i
.PHONY : player.cc.i

player.s: player.cc.s
.PHONY : player.s

# target to generate assembly for a file
player.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/player.cc.s
.PHONY : player.cc.s

world.obj: world.cc.obj
.PHONY : world.obj

# target to build an object file
world.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/world.cc.obj
.PHONY : world.cc.obj

world.i: world.cc.i
.PHONY : world.i

# target to preprocess a source file
world.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/world.cc.i
.PHONY : world.cc.i

world.s: world.cc.s
.PHONY : world.s

# target to generate assembly for a file
world.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GAYME.dir\build.make CMakeFiles/GAYME.dir/world.cc.s
.PHONY : world.cc.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... GAYME
	@echo ... gamestate.obj
	@echo ... gamestate.i
	@echo ... gamestate.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... motion.obj
	@echo ... motion.i
	@echo ... motion.s
	@echo ... object.obj
	@echo ... object.i
	@echo ... object.s
	@echo ... player.obj
	@echo ... player.i
	@echo ... player.s
	@echo ... world.obj
	@echo ... world.i
	@echo ... world.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

